# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries
name: build Python Package

on: push

jobs:
  deploy:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.6'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools
          pip install -r requirements.txt
      - name: Build
        run: |
          pyinstaller -F -w --distpath . main.py
          dir
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: main
          path: main.exe
          retention-days: 3